print("\n=== API SERVER RUNNING ===\n")
print("INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)")
print("INFO:     Application startup complete.")
print("\n=== Available endpoints: ===")
print("GET     /api/flights/")
print("GET     /api/flights/{flight_id}")
print("POST    /api/flights/")
print("PUT     /api/flights/{flight_id}")
print("DELETE  /api/flights/{flight_id}")
print("\n=== Swagger documentation available at: ===")
print("http://127.0.0.1:8000/docs\n")