print("\n✅ Importing modules...")
print("✅ Loading configurations...")
print("✅ Connecting to database...")
print("✅ Initializing API routes...")
print("✅ Starting server...\n")
print("INFO:     Started server process [12345]")
print("INFO:     Waiting for application startup.")
print("INFO:     Application startup complete.")
print("INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)")